# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-13 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(max_length=500, upload_to='products')),
                ('price', models.IntegerField()),
                ('shipping_charges', models.IntegerField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('estimated_arrival', models.CharField(max_length=10)),
            ],
        ),
    ]
